version: "3"
services:

  web:
    image: "tryton/tryton:latest"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ~/tryton:/root/flask
    tty:
      true
      
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=testusr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - ~/tryton/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      

